### ISSUE TITLE
Pyspark UDF function local debugging 

### ISSUE THREAD

**Issue by Sutyke** [bradyjiang/pyspark_xray#1]
Hi ,

I would like to debug locally UDF function  def pandas_function(url_json) in the example code below. Is it possible in your package, could you please provide example?

Thanks in advance

Example Code

```
import pandas as pd
import pyspark
from pyspark.sql import Row
from pyspark.sql.types import StructType, StructField, IntegerType,StringType
spark = pyspark.sql.SparkSession.builder.appName("test") \
    .master('local[*]') \
    .getOrCreate()
sc = spark.sparkContext

# Create initial dataframe respond_sdf
d_list = [('api_1',"{'api': ['api_1', 'api_1', 'api_1'],'A': [1,2,3], 'B': [4,5,6] }"),
            (' api_2', "{'api': ['api_2', 'api_2', 'api_2'],'A': [7,8,9], 'B': [10,11,12] }")]

schema = StructType([
  StructField('url', StringType(), True),
  StructField('content', StringType(), True)
  ])

jsons = sc.parallelize(rdd_list)
respond_sdf = spark.createDataFrame(jsons, schema)

# Pandas UDF 
def pandas_function(url_json):
# Here I want to place breakpoint
    for df in url_json:
        yield pd.DataFrame(eval(df['content'][0]))

# Pnadas UDF transformation applied to respond_sdf
transformed_df = respond_sdf.mapInPandas(pandas_function, "api string, A int, B int")
transformed_df.show()
```

**Comment by bradyjiang** [comment]
Sorry for late reply.  I will take a look at this now.

**Comment by bradyjiang** [comment]
Done, added wrapper function `wrapper_sdf_mapinvalues`, and check out the [example code](https://github.com/bradyjiang/pyspark_xray/blob/master/demo_app02/driver.py#L37-L41) that calls it.

**Comment by Sutyke** [comment]
Thanks for pyspark UDF  debugging wrapper, for some reason I'm getting error when running. any idea?

I cloned package and run pip install -e. and run code in VS Code. 

When I run [demo](https://github.com/bradyjiang/pyspark_xray/blob/master/demo_app02/driver.py ), I get: 

 Traceback (most recent call last):
  File "/home/d/anaconda3/envs/yf/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/d/anaconda3/envs/yf/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/d/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/d/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/d/.vscode/extensions/ms-python.python-2021.1.502429796/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/d/anaconda3/envs/yf/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/d/anaconda3/envs/yf/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/d/anaconda3/envs/yf/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/d/OneDrive/01_Data/Archive/debug_udf.py", line 39, in <module>
    transformed_df = utils_debugger.wrapper_sdf_mapinvalues(input_sdf=respond_sdf
  File "/home/d/pyspark_xray/pyspark_xray/utils_m.py", line 33, in wrapper_sdf_mapinvalues
    output_sdf = input_sdf.mapInValues(func=func, schema=output_schema)
  File "/home/d/spark/python/pyspark/sql/dataframe.py", line 1400, in __getattr__
    raise AttributeError(
AttributeError: 'DataFrame' object has no attribute 'mapInValues'

**Comment by bradyjiang** [comment]
is your pyspark version 3.0.1?  if not, you will get that error

**Comment by Sutyke** [comment]
I have 3.0.1, as mapInPandas came in this version, problem is in the wrapper.

1)  When I run :

```
transformed_df = respond_sdf.mapInPandas(pandas_function, "api string, A int, B int")
```

+-----+---+---+                                                                 
|  api|  A|  B|
+-----+---+---+
|api_1|  1|  4|
|api_1|  2|  5|
|api_1|  3|  6|
|api_2|  7| 10|
|api_2|  8| 11|
|api_2|  9| 12|
+-----+---+---+


2) When I run wrapper:
```
transformed_df = utils_debugger.wrapper_sdf_mapinvalues(input_sdf=respond_sdf
                                           , func=pandas_function
                                           , spark_session=spark
                                           , debug_flag=const_xray.CONST_BOOL_LOCAL_MODE
                                            , output_schema="api string, A int, B int")
```
I get error above

**Comment by Sutyke** [comment]
I found the problem:
1) I had to change `debug_flag=const_xray.CONST_BOOL_LOCAL_MODE` to `debug_flag=True`
2) there is mixed naming convention, wrapper_sdf_mapinvalues should be wrapper_sdf_mapInPandas and function in utils_m.py should be mapInPandas instead of mapinvalues .

Thanks a lof for great package, it saves a lot of time with debugging pyspark!!!
